---
- name: Automate workstation setup after fresh install
  hosts: localhost
  become: True
  become_user: john

  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
