---
- name: Automate workstation setup after fresh install
  hosts: localhost
  become: True
  sudo: True
  sudo_user: john
  sudo_ask_pass: True

  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
