- name: Automate installation of packages on workstation after fresh install
  hosts: localhost
  become: yes

  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages-xfce.yml
