- name: Install The Goods
  apt:
    pkg:
    - firmware-linux-free
    - firmware-linux-nonfree
    - firmware-realtek
    - intel-microcode
    - htop
    - nmap
    - tmux
    - memtest86+
    - mlocate
    - gamin
    - zsh
    - vim
    - tuned
    - haveged
    - bzr
    - git
    - subversion
    - mercurial
    - chrony
    - build-essential
    - aptitude
    - argyll
    - icc-profiles
    - xserver-xorg
    - x11-xserver-utils
    - i3
    - xfce4-settings
    - xfce4-terminal
    - nitrogen
    - pulseaudio
    - pavucontrol
    - pasystray
    - lightdm
    - network-manager
    - network-manager-gnome
    - firefox-esr
    - geary
    - thunar
    - thunar-volman
    - gvfs-backends
    - dmz-cursor-theme
    - ibus
    - galculator
    - faba-icon-theme
    - moka-icon-theme
    - greybird-gtk-theme
